create table "public"."catalog" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "minquan" bigint,
    "price" bigint,
    "img" text
);


CREATE UNIQUE INDEX catalog_pkey ON public.catalog USING btree (id);

alter table "public"."catalog" add constraint "catalog_pkey" PRIMARY KEY using index "catalog_pkey";


